---
title: "Guided Ex. 2: Baseball Salary Analysis"
author: "Robert Alward"
date: "2/25/2021"
output: html_document
---

```{r loading data and libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)

player_data <- read.csv("Master.csv")
pitching_data <- read.csv("Pitching.csv")
salary_data <- read.csv("Salaries.csv")
inflation_index <- read.csv("inflation.csv")

```


## Graph 1: 

```{r Graph 1, warning=FALSE, message=FALSE, results='hide'}

### 1. Earned Run Average Boxplot  

pitching_data$yearID <- as.factor(pitching_data$yearID)

ggplot(pitching_data)+
  geom_boxplot(aes(x=yearID, y=ERA))
```


## Graph 2: 


```{r Graph 2, warning=FALSE, message=FALSE, results='hide'}

### 1. Median Earned Run Average Line plot  

summary_ERA <- summarize(group_by(pitching_data, yearID), 
                            Q1 = quantile(ERA,.25,na.rm=T),
                            median = median(ERA,na.rm=T),
                            Q3 = quantile(ERA,.75,na.rm=T),
                            min=min(ERA,na.rm=T),
                            max=max(ERA,na.rm=T))

summary_ERA$yearID <- as.numeric(as.character(summary_ERA$yearID))

ggplot(summary_ERA) +
  geom_line(aes(x=yearID,y=median))

```

## Graph 3: 

```{r Graph 3, warning=FALSE, message=FALSE, results='hide'}

### 2.ERA Ribbon graph showing range from first and third quartiles with the median ERA 

ggplot(summary_ERA) +
  geom_line(aes(x=yearID, y=median)) +
  geom_ribbon(aes(x=yearID, ymin=Q1, ymax=Q3), fill="lightgreen") +
  geom_line(aes(x=yearID, y=median),color="blue")

```

## Graph 4: 

```{r Graph 4, warning=FALSE, message=FALSE, results='hide'}

#4. Proportion of Pitchers (pitching at least 10 games) \n With Low and High ERAs by Year

pitching_data$ERA <- as.numeric(pitching_data$ERA)

head(pitching_data)

pitching_data_G <- filter(pitching_data, G >= 10)

pitching_data_G$yearID <- as.numeric(as.character(pitching_data_G$yearID))

summary_ERA_2 <- summarize(group_by(pitching_data_G, yearID),
                              six_plus_pitchers=mean(ERA >= 6,na.rm=T), 
                              three_under_pitchers=mean(ERA <= 3,na.rm=T))

ggplot(summary_ERA_2) + 
  geom_line(aes(x=yearID,y=(six_plus_pitchers),color= "Six or Higher")) +
  geom_line(aes(x=yearID,y=(three_under_pitchers),color= "Three or Under" )) +
  scale_color_manual(values=c("Three or Under" = "darkblue", "Six or Higher" = "red"),name = ("ERA")) +
  labs(title="Proportion of Pitchers (pitching at least 10 games) \n With Low and High ERAs by Year",
         x="Year",y="Proportion") +
  theme_classic()
```


## Graph 5:

Data Organization

```{r Graph 5, warning=FALSE, message=FALSE, results='hide'}

### 5.1 Data Filtering Work

# 5.1.a Birth Place Data
head(player_data)

# 5.1.b Filtering out US and Foreign Born players
USA_born <- filter(player_data, birthCountry == "USA")
Foreign_born <- filter(player_data, birthCountry != "USA")

# 5.1.c Joining the birthplace data with salary data
USA_born_right <- inner_join(salary_data, USA_born, by="playerID")
Foreign_born_right <- inner_join(salary_data, Foreign_born, by="playerID")

# 5.1.d Adding variables to identify US or Not US born players
USA_born_right$birth_place <- "Born in USA" 
Foreign_born_right$birth_place <- "Born outside USA"

# 5.1.e Binding the data back together
complete_birth_data <- rbind(USA_born_right,Foreign_born_right)
head(complete_birth_data)

### 5.2 Data Combination Work

# 5.2.a Creating Summary Data for combined birth place data
summary_birth <- summarize(group_by(complete_birth_data, yearID, birth_place), 
                           Q1 = quantile(salary,.25,na.rm=T),
                           median=median(salary,na.rm=T),
                           Q3 = quantile(salary,.75,na.rm=T), 
                           min=min(salary,na.rm=T), 
                           max=max(salary,na.rm=T))

summary_birth$yearID <- as.numeric(as.character(summary_birth$yearID))
head(summary_birth)


# 5.2.b Adding in the inflation factor
names(inflation_index)[1] <- "yearID"
inflation_index$yearID <- as.numeric(as.character(inflation_index$yearID))
head(inflation_index)

summary_birth_left <- left_join(summary_birth,inflation_index, by = "yearID")
summary_birth_left[summary_birth_left$yearID==2015,"inflation2015"]<-1
tail(summary_birth_left)

summary_birth <- mutate(summary_birth_left, 
                         median_inflation_adjusted = median*inflation2015,
                         Q1_inflation_adjusted = Q1*inflation2015, 
                         Q3_inflation_adjusted = Q3*inflation2015, 
                         min_inflation_adjusted = min*inflation2015,
                         max_inflation_adjusted = max*inflation2015)
head(summary_birth)
```


Graph Output

```{r Graph 5 Output, warning=FALSE, message=FALSE, results='hide'}


## 5.3 Graph Creation of Annual Salary Adjusted for Inflation

ggplot(summary_birth)+
  geom_ribbon(aes(x=yearID, ymin=Q1_inflation_adjusted, 
                  ymax=Q3_inflation_adjusted,fill=birth_place ),alpha = 0.4)+
  geom_line(aes(x=yearID, y=median_inflation_adjusted, color= birth_place ),size=1.2) +
  scale_fill_discrete(name = "Middle 50% of Earners")+
  scale_color_discrete(name = "Median Salary") + 
  scale_y_continuous(labels = scales::dollar)+
  labs(y="Annual Salary  \n (Adjusted for Inflation)", 
       x="Year",
       title="Salaries of Middle 50% of Earners in Major League Baseball") +
  theme_minimal()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
